"""Add iBeacon fields to Laptop model

Revision ID: 46864b63b8ee
Revises: c3cb15a249d3
Create Date: 2025-07-31 19:37:21.515037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46864b63b8ee'
down_revision = 'c3cb15a249d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laptop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ibeacon_uuid', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('ibeacon_major', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ibeacon_minor', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laptop', schema=None) as batch_op:
        batch_op.drop_column('ibeacon_minor')
        batch_op.drop_column('ibeacon_major')
        batch_op.drop_column('ibeacon_uuid')

    # ### end Alembic commands ###
