"""Add iBeacon MAC address column

Revision ID: 7c685ee7ccb7
Revises: 7e20bc9914be
Create Date: 2025-08-02 07:36:58.804244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c685ee7ccb7'
down_revision = '7e20bc9914be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laptop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ibeacon_mac_address', sa.String(length=17), nullable=True))

    with op.batch_alter_table('sensor_reading', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ibeacon_mac_address', sa.String(length=17), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_reading', schema=None) as batch_op:
        batch_op.drop_column('ibeacon_mac_address')

    with op.batch_alter_table('laptop', schema=None) as batch_op:
        batch_op.drop_column('ibeacon_mac_address')

    # ### end Alembic commands ###
