"""Add ultrasonic intrusion flag to SensorReading

Revision ID: 7e20bc9914be
Revises: 827f9b963a65
Create Date: 2025-08-02 05:23:40.360580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e20bc9914be'
down_revision = '827f9b963a65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_reading', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultrasonic_intrusion_detected', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_reading', schema=None) as batch_op:
        batch_op.drop_column('ultrasonic_intrusion_detected')

    # ### end Alembic commands ###
