"""Add four ultrasonic sensor columns

Revision ID: 827f9b963a65
Revises: 46864b63b8ee
Create Date: 2025-08-01 22:00:46.519663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '827f9b963a65'
down_revision = '46864b63b8ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_reading', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultrasonic_distance_1_cm', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ultrasonic_distance_2_cm', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ultrasonic_distance_3_cm', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ultrasonic_distance_4_cm', sa.Float(), nullable=True))
        batch_op.drop_column('ultrasonic_distance_cm')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_reading', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultrasonic_distance_cm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('ultrasonic_distance_4_cm')
        batch_op.drop_column('ultrasonic_distance_3_cm')
        batch_op.drop_column('ultrasonic_distance_2_cm')
        batch_op.drop_column('ultrasonic_distance_1_cm')

    # ### end Alembic commands ###
