"""Add SensorReading model and update Laptop model for sensor data

Revision ID: aef39abcd431
Revises: 
Create Date: 2025-07-31 14:47:02.167132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aef39abcd431'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('laptop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('serial_number', sa.String(length=120), nullable=True),
    sa.Column('is_stolen', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('laptop', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_laptop_serial_number'), ['serial_number'], unique=True)

    op.create_table('sensor_reading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('ibeacon_uuid', sa.String(length=36), nullable=True),
    sa.Column('ibeacon_major', sa.Integer(), nullable=True),
    sa.Column('ibeacon_minor', sa.Integer(), nullable=True),
    sa.Column('ibeacon_rssi', sa.Integer(), nullable=True),
    sa.Column('ultrasonic_distance_cm', sa.Float(), nullable=True),
    sa.Column('laptop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['laptop_id'], ['laptop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sensor_reading', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sensor_reading_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_reading', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sensor_reading_timestamp'))

    op.drop_table('sensor_reading')
    with op.batch_alter_table('laptop', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_laptop_serial_number'))

    op.drop_table('laptop')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
